In [1]:
first = 1

1

In [2]:
second = 'J'

'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

In [3]:
const MEANING_OF_LIFE = 42

42

In [4]:
second = 7

7

In [5]:
MEANING_OF_LIFE = 90

90

In [7]:
MEANING_OF_LIFE

90

In [10]:
function testfunc()
    x::String = "some text"
    #x=10 -> Error
end

testfunc (generic function with 1 method)

In [11]:
testfunc()

"some text"

In [12]:
function helloworld()
    println("HEllo World!")
end


function helloworld(count::Int)
    for i in 1:count
        println("Hello World ", i)
    end
end

helloworld (generic function with 2 methods)

In [13]:
helloworld()

HEllo World!


In [14]:
helloworld(3)

Hello World 1
Hello World 2
Hello World 3


In [15]:
a = Int16(1)

1

In [16]:
println(typeof(a))

Int16


In [17]:
b = Int(2000)
println(typeof(b))

Int64


In [18]:
c = UInt16(1)
println(typeof(c))

UInt16


In [19]:
d = 40
println(typeof(d))

Int64


In [24]:
println("Int8 typemax: " , typemax(Int8))
println("Int8 typemin: " , typemin(Int8))
println("Int32 typemax: " , typemax(Int32))
println("Int32 typemin: " , typemin(Int32))
println("Int64 typemax: " , typemax(Int64))
println("Int64 typemin: " , typemin(Int64))

Int8 typemax: 127
Int8 typemin: -128
Int32 typemax: 2147483647
Int32 typemin: -2147483648
Int64 typemax: 9223372036854775807
Int64 typemin: -9223372036854775808


In [25]:
println(Sys.WORD_SIZE)

64


In [27]:
# a = UInt8(300) Error

In [28]:
println(1.0 / 0.0)

Inf


In [29]:
println(1.0/Inf)

0.0


In [30]:
println(0.0/0.0)

NaN


In [31]:
println(zero(Float64))
println(one(UInt32))

0.0
1


In [37]:
mychar = 'x'

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [38]:
println(Int(mychar))

120


In [39]:
println(Char(120))

x


In [41]:
mystr = "This is a sample string in Julia"

"This is a sample string in Julia"

In [42]:
myotherstr = """
    Hello There
    This is a string
    """

"Hello There\nThis is a string\n"

In [43]:
println(length(mystr))

32


In [44]:
mystr[1]

'T': ASCII/Unicode U+0054 (category Lu: Letter, uppercase)

In [45]:
mystr[end]

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [46]:
mystr[end-3]

'u': ASCII/Unicode U+0075 (category Ll: Letter, lowercase)

In [69]:
println(mystr[2:end-1])

his is a sample string in Juli


In [70]:
for c in mystr
    print(c)
end

This is a sample string in Julia

In [72]:
w1 = "Hello"
w2 = "world"

println(w1 * ", " * w2 * ".")

Hello, world.


In [47]:
(3*4);

In [48]:
ans

12

In [49]:
if 5 == 5
    println("5 is 5")
end
if 5 < 2
    print("no")
else
    print("si senior")
end

5 is 5
si senior

In [50]:
function addnumbers(numberone, numbertwo)
    return(numberone += numbertwo)
end

addnumbers (generic function with 1 method)

In [51]:
addnumbers(5, 10)

15

In [52]:
sum([5, 10, 10])

25

In [53]:
array = [5, 10, 15, 20]

4-element Array{Int64,1}:
  5
 10
 15
 20

In [54]:
# iterative loop
for number in 10:20
    print(number)
end

1011121314151617181920

In [112]:
# while loop
number = 1
while number <= 5
    number += 1
    print(number)
end

23456

In [56]:
# recursive loop
function fact(n)
    if n == 1
        return(1)
    else
        return n * fact(n-1)
        println(n)
    end
end

fact (generic function with 1 method)

In [57]:
fact(5)

120

In [58]:
array = [5, 10, 15, 20]

4-element Array{Int64,1}:
  5
 10
 15
 20

In [59]:
newarray = []

for element in array
    if element == 10
        append!(newarray, element)
    elseif element == 20
        append!(newarray, element)
    end
end

println(newarray)

Any[10, 20]


In [60]:
println(array)

[5, 10, 15, 20]


In [61]:
array2 = [30, 40, 50, 60]

4-element Array{Int64,1}:
 30
 40
 50
 60

In [62]:
for (i, w) in zip(array, array2)
    println(i, w)
end

530
1040
1550
2060


In [66]:
Hello = "Hello World"

"Hello World"

In [67]:
function filterstring(input)
    validchars = ['H', 'W', 'l', 'r', 'o', 'd']
    for character in input
        if character in validchars
            print(character)
        end
    end
end

filterstring (generic function with 1 method)

In [68]:
filterstring(Hello)

HlloWorld

In [73]:
a = 5
b = 10

println("The result of $a + $b is $(a+b)")

The result of 5 + 10 is 15


In [74]:
round(30.5)

30.0

In [75]:
round(30.5, RoundUp)

31.0

In [76]:
y = 29.95
println(floor(y))
print(ceil(y))

29.0
30.0

In [77]:
z = -15
abs(z)

15

In [78]:
thestr = "This is some text"
printstyled(thestr)
println()
printstyled(thestr, bold=true)
println()
printstyled(thestr, bold = true, color=:red)

This is some text
This is some text
This is some text

In [81]:
print("What is your name? >>")
str = readline()
println("Hello ", str)

What is your name? >>

stdin>  Lukas


Hello Lukas


In [83]:
println(isascii("abc"))
println(isascii("αβγ"))
println()
println(isdigit('9'))
println(isdigit('a'))
println()
println(isspace(' '))
println(isspace('\r'))
println(isspace('\n'))
println(isspace('A'))

true
false

true
false

true
true
true
false


In [84]:
arr1 = [2,4,6,8,10]

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [88]:
arr1 .*2

5-element Array{Int64,1}:
  4
  8
 12
 16
 20

In [94]:
sqrt.(arr1)

5-element Array{Float64,1}:
 1.4142135623730951
 2.0
 2.449489742783178
 2.8284271247461903
 3.1622776601683795

In [89]:
f(x) = 3x

f (generic function with 1 method)

In [96]:
f.(arr1)

5-element Array{Int64,1}:
  6
 12
 18
 24
 30

In [98]:
x = 10
y = 20.0
z = "40"
j = "30.0"

"30.0"

In [99]:
c = Char(74)
println(c)

i = Int('J')
println(i)

J
74


In [100]:
flt1 = Float32(x)
int1 = Int16(y)
println(flt1, ", ", int1)

10.0, 20


In [104]:
a = parse(Int, z)
b = parse(Float64, j)
c = string(y)

println(a)
println(b)
println(c)

40
30.0
20.0


"20.0"

In [107]:
x = Char(281)
println(x)

# a = UInt8(x) error 281 too larg to fit in unsigned 8 bit int


ę


In [108]:
x = 5

5

In [109]:
println(x < 10 ? "x is less than 10" : "x is 10 or greater")

x is less than 10


In [110]:
for i in ["Bingo","Bango","Bongo","Irving"]
    println(i)
end

Bingo
Bango
Bongo
Irving


In [111]:
for i in 1:3, j in 2:4
    println(i, ", ", j)
end


1, 2
1, 3
1, 4
2, 2
2, 3
2, 4
3, 2
3, 3
3, 4


In [113]:
i = 1
while i <= 5
    println(i)
    global i += 1
end

1
2
3
4
5


In [114]:
teams = ("Giants", "Wizards", "Dragons", "Knights", "Kings")

("Giants", "Wizards", "Dragons", "Knights", "Kings")

In [116]:
for (idx, val) in enumerate(teams)
    println(idx, ", ", val)
end

1, Giants
2, Wizards
3, Dragons
4, Knights
5, Kings


In [119]:
for i in 1:10
    if i % 3 == 0
        continue
    elseif i > 7
        break
    end
    println(i)
end

1
2
4
5
7


In [120]:
function foo(a, b, z = 10)
    return (a + b) * z
end
println(foo(2, 3))
println(foo(2, 3, 5))

50
25


In [122]:
myfunc3(x, y) = (a = x - 1; 2a + y)

myfunc3 (generic function with 1 method)

In [123]:
myfunc3(3, 4)

8

In [124]:
function summit(args...)
    sum = 0
    for a in args
        sum += a
    end
    return sum
end

summit (generic function with 1 method)

In [125]:
println(summit(1, 5, 10))
println(summit(2, 4, 6, 8))

16
20


In [128]:
arg = -9

-9

In [132]:
try
    x = sqrt(arg)
    println(x)
catch ex
    println(ex)
finally
    println("This section always runs")
end

DomainError(-9.0, "sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).")
This section always runs


In [133]:
arr = [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [134]:
typeof(arr)

Array{Int64,1}

In [135]:
length(arr)

5

In [136]:
println("Element at pos 2 is ", arr[2])

Element at pos 2 is 2


In [141]:
# arrays can hold different types of values
arr2 = ["One", 2, true, 5.0,-4]
println(arr2)
println(typeof(arr2))

Any["One", 2, true, 5.0, -4]
Array{Any,1}


In [142]:
typeof(arr2)

Array{Any,1}

In [143]:
arr3  = Float64[]
push!(arr3, 1.0, 2.0, 3.0)

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [148]:
arr4 = zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [149]:
arr4 = ones(4)

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [150]:
arr5 = fill(5, 7)

7-element Array{Int64,1}:
 5
 5
 5
 5
 5
 5
 5

In [151]:
newarr = sort(arr, rev = true)

5-element Array{Int64,1}:
 5
 4
 3
 2
 1

In [152]:
sort!(newarr)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [155]:
strval = join(arr, "-")

"1-2-3-4-5"

In [156]:
tup = (1, 3.0, "five", 7, '9')

(1, 3.0, "five", 7, '9')

In [157]:
tup[3]

"five"

In [158]:
tup[2:4]

(3.0, "five", 7)

In [159]:
for i in tup
    println(i)
end

1
3.0
five
7
9


In [160]:
3 in tup

true

In [161]:
4 in tup

false

In [162]:
dimtup = ((1, 2), (3, 4), (5, 6))

((1, 2), (3, 4), (5, 6))

In [163]:
dimtup[3]

(5, 6)

In [164]:
dimtup[1][2]

2

In [165]:
namedtup = (a=1, b="two", c='3')

(a = 1, b = "two", c = '3')

In [167]:
namedtup[1]

1

In [168]:
namedtup.a

1

In [169]:
set1 = Set()

Set{Any}()

In [170]:
push!(set1, "a", 2, 5.0)

Set{Any} with 3 elements:
  2
  5.0
  "a"

In [171]:
set2 = Set([1, 2, 3, 4, 2, 5, 7, 1])

Set{Int64} with 6 elements:
  7
  4
  2
  3
  5
  1

In [173]:
#push!(set2, "abc")  -> Error bc not Int64

In [174]:
rainbow = Set{String}()

Set{String}()

In [176]:
push!(rainbow, "red", "orange", "yellow", "green", "blue", "indigo", "violet")

Set{String} with 8 elements:
  "indigo"
  "yellow"
  "orange"
  "yello"
  "blue"
  "green"
  "violet"
  "red"

In [177]:
"red" in rainbow

true

In [179]:
# rainbow[1] -> Error

In [180]:
primarycolors = Set(["red","yellow","green","blue"])
pastels = Set(["teal","pink","lavender","coral"])

Set{String} with 4 elements:
  "coral"
  "lavender"
  "pink"
  "teal"

In [181]:
commoncolors = intersect(rainbow, primarycolors)

Set{String} with 4 elements:
  "yellow"
  "blue"
  "green"
  "red"

In [182]:
allcolors = union(rainbow, pastels)

Set{String} with 12 elements:
  "indigo"
  "coral"
  "lavender"
  "green"
  "pink"
  "yellow"
  "orange"
  "yello"
  "violet"
  "teal"
  "blue"
  "red"

In [183]:
diffcolors = setdiff(rainbow, primarycolors)

Set{String} with 4 elements:
  "indigo"
  "orange"
  "yello"
  "violet"

In [184]:
d1 = Dict("a" => 1, "b" => 2, "c" => 3)

Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 1

In [185]:
d2 = Dict{String, String}()

Dict{String,String}()

In [186]:
d2["key1"] = "val1"

"val1"

In [187]:
d_test = Dict("a" => 1, "bobo" => 2.0, 'J' => "three", 3 => true)

Dict{Any,Any} with 4 entries:
  'J'    => "three"
  3      => true
  "bobo" => 2.0
  "a"    => 1

In [188]:
d1["b"]

2

In [189]:
d1["d"] = 4

4

In [190]:
d1

Dict{String,Int64} with 4 entries:
  "c" => 3
  "b" => 2
  "a" => 1
  "d" => 4

In [191]:
# Test to see if an item is in a dictionary
haskey(d1, "e")

false

In [192]:
haskey(d1, "d")

true

In [193]:
delete!(d1, "c")

Dict{String,Int64} with 3 entries:
  "b" => 2
  "a" => 1
  "d" => 4

In [194]:
keys(d1)

Base.KeySet for a Dict{String,Int64} with 3 entries. Keys:
  "b"
  "a"
  "d"

In [195]:
values(d1)

Base.ValueIterator for a Dict{String,Int64} with 3 entries. Values:
  2
  1
  4

In [196]:
for (key, value) in d1
    println(key, ", ", value)
end

b, 2
a, 1
d, 4


In [197]:
using Random

In [199]:
rand()

0.7413761134124626

In [200]:
for i in 1:3
    println(rand([1, 2, 3, 4, 5, 6]))
end

4
6
3


In [201]:
for i in 1:3
    println(rand(["a", "b", "c"]))
end

b
c
a


In [202]:
arr = rand(UInt8, 5)

5-element Array{UInt8,1}:
 0x7b
 0xf7
 0x99
 0xd1
 0x40

In [204]:
randstring("ABCD") #default length is 8

"BBDABDBB"

In [206]:
randstring('a':'z', 6)

"ublvmi"

In [208]:
vowels = ["A", "E", "I", "O", "U"]
Random.shuffle!(vowels)

5-element Array{String,1}:
 "U"
 "O"
 "E"
 "A"
 "I"

In [213]:
Random.seed!(1000)
println(rand())
println(rand())

0.6051120360474347
0.9173065075560396


In [214]:
Random.seed!(1000)
println(rand())
println(rand())

0.6051120360474347
0.9173065075560396


In [218]:
mystr = "Ångström"
teststr = "jμΛIα" # test string with some Greek characters

unicodestr = "AdamAndEve"

"AdamAndEve"

In [219]:
println("String length: ", length(teststr))
println("Size of String: ", sizeof(teststr))

println("String length: ", length(mystr))
println("Size of String: ", sizeof(mystr))

println("String length: ", length(unicodestr))
println("Size of String: ", sizeof(unicodestr))

String length: 5
Size of String: 8
String length: 8
Size of String: 10
String length: 10
Size of String: 10


In [220]:
teststr = "Hello " * "World"

"Hello World"

In [221]:
teststr = "ABCD"^3

"ABCDABCDABCD"

In [222]:
teststr = "Julia programming is awesome"

"Julia programming is awesome"

In [229]:
findnext("Julia", teststr, 0)

1:5

In [228]:
occursin("some", teststr)

true

In [230]:
teststr = lpad("Test String", 20)
println(teststr)
teststr = rpad("Test String", 20, '*')

         Test String


"Test String*********"

In [1]:
arr = ["Lions", "Tigers", "Bears"]

3-element Array{String,1}:
 "Lions"
 "Tigers"
 "Bears"

In [2]:
teststr  = join(arr, ", ", " and ")

"Lions, Tigers and Bears"

In [3]:
arr = ["Lions","Birds", "Dogs", "Cats", "Tigers", "Bears"]

6-element Array{String,1}:
 "Lions"
 "Birds"
 "Dogs"
 "Cats"
 "Tigers"
 "Bears"

In [7]:
teststr  = join(arr, ", ", " and ")

"Lions, Birds, Dogs, Cats, Tigers and Bears"

In [8]:
print("Current working directory: ")
println(pwd())

Current working directory: /home/lukas/Documents/programming/Julia


In [9]:
print("Current directory contents: ")
println(readdir())

Current directory contents: [".ipynb_checkpoints", "Ex_Files_Learning_Julia", "HelloWorld.jl", "learningjulia.ipynb", "test.jl"]


In [10]:
function createfile(filename::String, text::String = "This is some text")
    io = open(filename, "w")
    write(io, text)
    close(io)
end

createfile (generic function with 2 methods)

In [11]:
createfile("mytestfile.txt", "Hello World\n by Lukas Schumi")

In [12]:
createfile("another.txt")

In [13]:
function readfile(filename::String)
    io = open(filename, "r")
    content = read(io, String)
    println(content)
end

readfile (generic function with 1 method)

In [14]:
readfile("mytestfile.txt")

Hello World
 by Lukas Schumi


In [15]:
function appendtoafile(filename::String, text::String)
    io = open(filename, "a")
    write(io, text)
    close(io)
end

appendtoafile (generic function with 1 method)

In [20]:
appendtoafile("mytestfile.txt", "\nThis text was added")

In [21]:
readfile("mytestfile.txt")

Hello World
 by Lukas Schumi

This text was added


In [22]:
function renamefile()
    mv("mytestfile.txt", "newfilename.txt")
end

renamefile (generic function with 1 method)

In [23]:
renamefile()

"newfilename.txt"

In [24]:
# delete a file
# rm("newfilename.txt")

In [25]:
using Dates

In [26]:
d1 = Date(2018, 12, 22)
dt1 =DateTime(2019, 7, 28)

println("Date and DateTime:")
println(d1, "\n", dt1)

Date and DateTime:
2018-12-22
2019-07-28T00:00:00


In [27]:
df1 = DateFormat("y-m-d")
d2 = Date("2020-10-10", df1)

println(d2)

2020-10-10


In [29]:
df2 = DateFormat("d-m-y")
d2 = Date("13-11-2020", df2)

2020-11-13

In [30]:
d3 = Date(2019,12,22)
d4 = Date(2019,7,28)

2019-07-28

In [32]:
dt3 = DateTime(2020,1,1)
dt4 = DateTime(2020,12,31)

2020-12-31T00:00:00

In [34]:
d4<d3

true

In [35]:
dt4<dt3

false

In [36]:
d3 - d4

147 days

In [37]:
dt4-dt3

31536000000 milliseconds

In [38]:
Dates.year(d3)

2019

In [39]:
Dates.week(d4)

30

In [40]:
Dates.dayofweek(d3)

7

In [41]:
Dates.dayname(d3)

"Sunday"

In [42]:
Dates.isleapyear(d3)

false

In [43]:
Dates.firstdayofweek(d4)

2019-07-22

In [44]:
Dates.lastdayofmonth(d4)

2019-07-31

In [45]:
struct MyType
    field1::Int
    field2::String
end

In [46]:
x = MyType(10, "ABC")

MyType(10, "ABC")

In [48]:
x.field1

10

In [49]:
mutable struct MyMutableType
    field1::Int
    field2::String
end

In [50]:
x = MyMutableType(10, "ABC")

MyMutableType(10, "ABC")

In [51]:
x.field2 = "DEF"

"DEF"

In [52]:
x

MyMutableType(10, "DEF")

In [53]:
isa(x, MyMutableType)

true

In [54]:
isa(4, Int)

true

In [55]:
isa('r', Char)

true

In [57]:
isa(5, Float64)

false

In [58]:
arr1 = [2, 8, -3, -15, 5, -7, 9, 0, 11]

9-element Array{Int64,1}:
   2
   8
  -3
 -15
   5
  -7
   9
   0
  11

In [59]:
sort(arr1, by = abs)

9-element Array{Int64,1}:
   0
   2
  -3
   5
  -7
   8
   9
  11
 -15

In [60]:
arrtup = [(1, 2), (2, 1), (3, 5), (4, 0)]

4-element Array{Tuple{Int64,Int64},1}:
 (1, 2)
 (2, 1)
 (3, 5)
 (4, 0)

In [62]:
issorted(arrtup, by = x->x[1])
#1 2 3 4

true

In [65]:
issorted(arrtup, by = x->x[2])
#2 1 5 0

false

In [67]:
struct MyRect
    length::Int
    width::Int
end

In [68]:
# want to sort rectangles by area
# no area in struct
# build own sorting function

In [69]:
arr2 = [MyRect(12, 22), MyRect(10, 18),MyRect(7, 12),MyRect(9, 30)]
println(arr2)

MyRect[MyRect(12, 22), MyRect(10, 18), MyRect(7, 12), MyRect(9, 30)]


In [72]:
function comparearea(rect1::MyRect, rect2::MyRect)
    area1 = rect1.length * rect1.width
    area2 = rect2.length * rect2.width
    
    return area1 < area2
end

comparearea (generic function with 1 method)

In [73]:
sort(arr2, lt=comparearea)

4-element Array{MyRect,1}:
 MyRect(7, 12)
 MyRect(10, 18)
 MyRect(12, 22)
 MyRect(9, 30)

In [74]:
arr2

4-element Array{MyRect,1}:
 MyRect(12, 22)
 MyRect(10, 18)
 MyRect(7, 12)
 MyRect(9, 30)

In [75]:
sort!(arr2, lt=comparearea)

4-element Array{MyRect,1}:
 MyRect(7, 12)
 MyRect(10, 18)
 MyRect(12, 22)
 MyRect(9, 30)

In [76]:
arr2

4-element Array{MyRect,1}:
 MyRect(7, 12)
 MyRect(10, 18)
 MyRect(12, 22)
 MyRect(9, 30)